// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-southeast-2",
    "aws_cognito_identity_pool_id": "ap-southeast-2:423b7af4-9a1d-4b47-a277-e5efd406e7f9",
    "aws_cognito_region": "ap-southeast-2",
    "aws_user_pools_id": "ap-southeast-2_oWUKXkJlb",
    "aws_user_pools_web_client_id": "224pfj1u500ths5pfaupafcfni",
    "aws_appsync_graphqlEndpoint": "https://ovc5l7ydqjgk7kkwz6ouxzsxki.appsync-api.ap-southeast-2.amazonaws.com/graphql",
    "aws_appsync_region": "ap-southeast-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
